name: Deployment pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, closed]

jobs:
  Simple_development_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        if: github.event.action == 'opened' && github.action.pull_request.merged == false
        with:
          node-version: "20"
      - name: Install dependencies
        if: github.event.action == 'opened' && github.action.pull_request.merged == false
        run: npm install
      - name: Lint
        if: github.event.action == 'opened' && github.action.pull_request.merged == false
        run: npm run eslint
      - name: Build
        if: github.event.action == 'opened' && github.action.pull_request.merged == false
        run: npm run build
      - name: Unit test
        if: github.event.action == 'opened' && github.action.pull_request.merged == false
        run: npm run test
      - name: e2e tests
        if: github.event.action == 'opened' && github.action.pull_request.merged == false
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Set up Fly.io
        if: github.event.action == 'closed' && github.action.pull_request.merged == true
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy App
        if: github.event.action == 'closed' && github.action.pull_request.merged == true
        run: npm run deploy:fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
