name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

jobs:
  Build_and_Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests (Only on merge)
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
  Deploy_app:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy App
        run: npm run deploy:fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
