name: Test stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Commit messages
        env:
          RESULT: ${{ contains(join(github.event.commits.*.message,', '),'#skip')}}
        run: |
          echo "$RESULT"
          if[$RESULT]
          then
            echo "Commit message contains skip"
          else
          echo "Commit message does not contain skip"
          fi
