name: Test stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Commit messages
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message,', ')}}
        run: |
          echo "$COMMIT_MESSAGES"
